<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>855e44ba-0b7e-475b-932a-c1c3340dfd5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.row .col-md-6:nth-child(1) .grid.full-width svg circle:nth-child(1)&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>1aa3496a-41da-43d4-ab83-a78f5980f404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>183</value>
      <webElementGuid>f6458149-c76c-4199-b285-fade77734075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>129.10000000000002</value>
      <webElementGuid>8c3d26dd-ae7a-4100-a57f-efe8cae90cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>e29a0611-384b-4155-8f80-31f93d08ff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>38ca64c8-e58c-4e01-93f7-6cc37a499329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>040d8561-efae-4438-81ef-29a8cd5da786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#3366cc</value>
      <webElementGuid>dd072822-7282-4f12-a688-746a1c6e6507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactgooglegraph-2&quot;)/div[1]/div[1]/div[1]/svg[1]/g[2]/g[2]/g[1]/circle[4]</value>
      <webElementGuid>89d0b7d1-c711-473c-abe9-7ffc92f83347</webElementGuid>
   </webElementProperties>
</WebElementEntity>
