<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>855e44ba-0b7e-475b-932a-c1c3340dfd5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>2acb1aec-a61f-4e09-886b-a4e18462f2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>183</value>
      <webElementGuid>01dfd8a9-fbae-4dbd-bc75-97ac61de1265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>129.10000000000002</value>
      <webElementGuid>9b48ce02-a3ac-45cf-ab5b-42ae7dc7c569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>9db5f98a-223b-4ade-aa2d-9ddb3d84e60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f7440be7-be47-4f9e-a9af-9ea074ed8a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22c1a059-7ca7-41c7-b0a7-58091489f12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#3366cc</value>
      <webElementGuid>d69dec40-408f-4450-896d-22c9612eebef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactgooglegraph-2&quot;)/div[1]/div[1]/div[1]/svg[1]/g[2]/g[2]/g[1]/circle[4]</value>
      <webElementGuid>ffa87991-ebbe-4c1c-bd46-8b3a0c5519a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
