<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>855e44ba-0b7e-475b-932a-c1c3340dfd5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.row .col-md-6:nth-child(1) .grid.full-width svg circle:nth-child(1)&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>85bf03e4-1be3-41fa-8956-30f7bc596426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>183</value>
      <webElementGuid>dd3b45ba-83c1-4233-aded-0f84e6c244e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>129.10000000000002</value>
      <webElementGuid>4bafc6bd-4f1b-4a9a-91e7-02c3c09195eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>2fb4c66f-e1cd-4c1e-9eaf-8ea0eaf4a878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>3439d217-e49b-4a64-9803-6779d900c281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2784a19-5b6b-496a-9778-999fbae1b28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#3366cc</value>
      <webElementGuid>75ce761a-bd3d-47d7-abfb-ee94c9249ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactgooglegraph-2&quot;)/div[1]/div[1]/div[1]/svg[1]/g[2]/g[2]/g[1]/circle[4]</value>
      <webElementGuid>93ecac14-7696-4e33-a01c-4fa491458dd6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
