<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vitals</name>
   <tag></tag>
   <elementGuidId>1e49f78a-ec37-4170-83b2-2b7f4d85f786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-sidebar']/ul/li[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>941a6b36-e277-4d1d-854a-aba1144960ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-title</value>
      <webElementGuid>20ec3ffd-2048-4c1d-a303-ed2c00101c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vitals</value>
      <webElementGuid>4c83e82e-23e1-428d-b480-7f812289ce19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-sidebar&quot;)/ul[@class=&quot;navigation-menu&quot;]/li[@class=&quot;white-bg&quot;]/a[@class=&quot;sidebar-link sidebar-border-zero&quot;]/span[@class=&quot;link-title&quot;]</value>
      <webElementGuid>75356286-f898-4f23-9791-e12eb5fbb5a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-sidebar']/ul/li[9]/a/span</value>
      <webElementGuid>2f3847ff-d6cc-4d04-b310-63c373442913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/span</value>
      <webElementGuid>4304a320-4ac1-4065-98a6-b14a56759045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vitals' or . = 'Vitals')]</value>
      <webElementGuid>76cc1a7c-47e2-45bc-b295-4fd0085338b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
